
name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]  # or your default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

name: Set up Node.js uses: actions/setup-node@v3 with: node-version: 16 # Use appropriate version
name: Install dependencies
run: npm ci  # or yarn install

name: Build
run: npm run build  # or yarn build

name: Deploy
uses: JamesIves/github-pages-deploy-action@v4
with:
  folder: dist  # or your build output folder
  branch: gh-pages