name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # ✅ Upgrade to Node.js 18 or later
          cache: "npm"

      - name: Install dependencies
        run: npm ci # or yarn install

      - name: Build project
        run: npm run build # Ensures Vite builds correctly

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist # Change if your build output is different
